// Generated by gencpp from file tutorial_vision/CircleDetectResult.msg
// DO NOT EDIT!


#ifndef TUTORIAL_VISION_MESSAGE_CIRCLEDETECTRESULT_H
#define TUTORIAL_VISION_MESSAGE_CIRCLEDETECTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tutorial_vision/CircleInfo.h>

namespace tutorial_vision
{
template <class ContainerAllocator>
struct CircleDetectResult_
{
  typedef CircleDetectResult_<ContainerAllocator> Type;

  CircleDetectResult_()
    : header()
    , height(0)
    , width(0)
    , circles()  {
    }
  CircleDetectResult_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , height(0)
    , width(0)
    , circles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _height_type;
  _height_type height;

   typedef uint32_t _width_type;
  _width_type width;

   typedef std::vector< ::tutorial_vision::CircleInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tutorial_vision::CircleInfo_<ContainerAllocator> >> _circles_type;
  _circles_type circles;





  typedef boost::shared_ptr< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> const> ConstPtr;

}; // struct CircleDetectResult_

typedef ::tutorial_vision::CircleDetectResult_<std::allocator<void> > CircleDetectResult;

typedef boost::shared_ptr< ::tutorial_vision::CircleDetectResult > CircleDetectResultPtr;
typedef boost::shared_ptr< ::tutorial_vision::CircleDetectResult const> CircleDetectResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_vision::CircleDetectResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_vision::CircleDetectResult_<ContainerAllocator1> & lhs, const ::tutorial_vision::CircleDetectResult_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.circles == rhs.circles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_vision::CircleDetectResult_<ContainerAllocator1> & lhs, const ::tutorial_vision::CircleDetectResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "920a6314571c6b3ce53335defc76681a";
  }

  static const char* value(const ::tutorial_vision::CircleDetectResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x920a6314571c6b3cULL;
  static const uint64_t static_value2 = 0xe53335defc76681aULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_vision/CircleDetectResult";
  }

  static const char* value(const ::tutorial_vision::CircleDetectResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 height\n"
"uint32 width\n"
"tutorial_vision/CircleInfo[] circles\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tutorial_vision/CircleInfo\n"
"float64 center_x\n"
"float64 center_y\n"
"float64 radius\n"
;
  }

  static const char* value(const ::tutorial_vision::CircleDetectResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.circles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CircleDetectResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_vision::CircleDetectResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_vision::CircleDetectResult_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "circles[]" << std::endl;
    for (size_t i = 0; i < v.circles.size(); ++i)
    {
      s << indent << "  circles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tutorial_vision::CircleInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.circles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_VISION_MESSAGE_CIRCLEDETECTRESULT_H
